"""
agent/mcp_test_generator.py
---------------------------
Mode 1 (TEST_GEN_MODE=mcp, TEST_CASE_MODE=false):
  Uses Playwright to navigate the live app, discover pages/forms/elements,
  and generates test scripts from real browser interactions.

Mode 2 (TEST_GEN_MODE=mcp, TEST_CASE_MODE=true):
  Reads test cases from CSV (generated by test_case_generator.py),
  then uses Playwright to navigate the app and generate test scripts
  driven by those test cases.

Both modes produce Playwright pytest scripts in:
  scripts/<repo>/dev/playwright/mcp_*.py
"""

import json
import os
import re
import logging
from typing import List, Optional

from agent.llm_provider import llm_available, llm_chat

logger = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')


def _write_file(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Written: {path}")


def _discover_app(base_url: str) -> dict:
    """
    Launch a headless browser, navigate to the app, and extract:
    - Page title
    - Navigation links / tabs
    - Forms with their inputs and buttons
    - Tables
    - Key interactive elements
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.error("Playwright not installed. Run: pip install playwright && python -m playwright install chromium")
        return {}

    discovery = {
        "title": "",
        "url": base_url,
        "tabs": [],
        "forms": [],
        "tables": [],
        "links": [],
        "buttons": [],
    }

    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_viewport_size({"width": 1280, "height": 720})

            page.goto(base_url, wait_until="networkidle", timeout=15000)
            discovery["title"] = page.title()

            # Discover tabs / navigation
            tabs = page.query_selector_all("[id^='tab-'], .nav-tab, .tab-link, nav a, .nav-link")
            for tab in tabs:
                tab_id = tab.get_attribute("id") or ""
                tab_text = tab.inner_text().strip()
                if tab_text:
                    discovery["tabs"].append({"id": tab_id, "text": tab_text})

            # Discover all pages by clicking tabs
            pages_data = [_extract_page_elements(page, base_url, "home")]

            for tab_info in discovery["tabs"]:
                tab_id = tab_info["id"]
                if not tab_id:
                    continue
                try:
                    page.click(f"#{tab_id}")
                    page.wait_for_timeout(500)
                    page_data = _extract_page_elements(page, base_url, tab_id.replace("tab-", ""))
                    pages_data.append(page_data)
                except Exception as e:
                    logger.warning(f"Could not click tab {tab_id}: {e}")

            discovery["pages"] = pages_data
            browser.close()

    except Exception as e:
        logger.error(f"App discovery failed: {e}")

    return discovery


def _extract_page_elements(page, base_url: str, page_name: str) -> dict:
    """Extract forms, inputs, buttons, tables from the current page state."""
    data = {"name": page_name, "forms": [], "tables": [], "buttons": []}

    # Forms
    forms = page.query_selector_all("form")
    for form in forms:
        form_id = form.get_attribute("id") or ""
        inputs = []
        for inp in form.query_selector_all("input, select, textarea"):
            inp_id = inp.get_attribute("id") or ""
            inp_name = inp.get_attribute("name") or ""
            inp_type = inp.get_attribute("type") or "text"
            inp_placeholder = inp.get_attribute("placeholder") or ""
            if inp_id or inp_name:
                inputs.append({
                    "id": inp_id, "name": inp_name,
                    "type": inp_type, "placeholder": inp_placeholder,
                })
        btns = []
        for btn in form.query_selector_all("button, input[type='submit']"):
            btns.append(btn.inner_text().strip() or btn.get_attribute("value") or "Submit")

        data["forms"].append({
            "form_id": form_id,
            "inputs": inputs,
            "buttons": btns,
        })

    # Tables
    tables = page.query_selector_all("table")
    for tbl in tables:
        tbl_id = tbl.get_attribute("id") or ""
        headers = [th.inner_text().strip() for th in tbl.query_selector_all("th")]
        row_count = len(tbl.query_selector_all("tbody tr"))
        data["tables"].append({"id": tbl_id, "headers": headers, "rows": row_count})

    # Standalone buttons
    standalone_btns = page.query_selector_all("button:not(form button)")
    for btn in standalone_btns:
        btn_id = btn.get_attribute("id") or ""
        btn_text = btn.inner_text().strip()
        if btn_text:
            data["buttons"].append({"id": btn_id, "text": btn_text})

    return data


def _generate_mcp_scripts_with_llm(discovery: dict, output_dir: str) -> List[str]:
    """Mode 1: Use LLM + discovered app structure to generate Playwright tests."""
    base_url = discovery.get("url", "http://localhost:8000")
    app_title = discovery.get("title", "App")

    pages_desc = []
    for pg in discovery.get("pages", []):
        desc = f"\nPage: {pg['name']}"
        for form in pg.get("forms", []):
            inputs_desc = ", ".join(
                f"{i['id'] or i['name']}({i['type']})" for i in form.get("inputs", []))
            desc += f"\n  Form #{form['form_id']}: inputs=[{inputs_desc}], buttons={form.get('buttons', [])}"
        for tbl in pg.get("tables", []):
            desc += f"\n  Table #{tbl['id']}: columns={tbl['headers']}"
        pages_desc.append(desc)

    tabs_desc = ", ".join(f"#{t['id']}({t['text']})" for t in discovery.get("tabs", []))
    full_structure = "\n".join(pages_desc)

    prompt = f"""Generate a comprehensive Playwright pytest test suite for this web application.

App: {app_title}
URL: {base_url}
Tabs/Navigation: {tabs_desc}

Application Structure:
{full_structure}

Generate Python Playwright tests that:
1. Test each page loads correctly
2. Test each form submission with valid data (positive tests)
3. Test each form with invalid/empty data (negative tests)
4. Test navigation between tabs
5. Test a full user journey across all pages
6. Test table data appears after form submissions

Requirements:
- import os, time, pytest from playwright.sync_api import Page, expect
- BASE_URL = os.getenv("SFCC_SITE_URL", "{base_url}")
- Use actual element IDs from the structure above (e.g. page.fill("#{{}}", "value"))
- Use expect() assertions
- Class TestMCPGenerated with descriptive test methods
- Include both positive and negative test cases
- Add performance assertions (page load < 5s)

Output ONLY valid Python code, no markdown fences."""

    try:
        response = llm_chat(prompt, temperature=0.2,
                            system="You are a QA automation expert. Generate comprehensive Playwright test scripts.")
        script = _strip_fences(response)
        path = os.path.join(output_dir, "mcp_generated_test.py")
        _write_file(path, script)
        return [path]
    except Exception as e:
        logger.error(f"LLM MCP script generation failed: {e}")
        return []


def _generate_mcp_scripts_template(discovery: dict, output_dir: str) -> List[str]:
    """Mode 1 fallback: Generate Playwright tests from templates when LLM unavailable."""
    base_url = discovery.get("url", "http://localhost:8000")
    app_title = discovery.get("title", "App")
    tabs = discovery.get("tabs", [])
    pages = discovery.get("pages", [])

    test_methods = []

    # Page load test
    test_methods.append(f'''
    def test_homepage_loads(self, page: Page):
        """Verify homepage loads with correct title."""
        page.goto(BASE_URL)
        expect(page).to_have_title("{app_title}")
''')

    # Tab navigation tests
    for tab in tabs:
        tab_id = tab["id"]
        tab_text = tab["text"]
        if not tab_id:
            continue
        slug = _slugify(tab_text)
        test_methods.append(f'''
    def test_navigate_{slug}(self, page: Page):
        """Navigate to {tab_text} tab."""
        page.goto(BASE_URL)
        page.click("#{tab_id}")
        page.wait_for_timeout(500)
''')

    # Form tests
    for pg in pages:
        for form in pg.get("forms", []):
            form_id = form.get("form_id", "")
            if not form_id:
                continue
            slug = _slugify(form_id)
            inputs = form.get("inputs", [])

            # Positive test - fill all fields
            fill_lines = []
            for inp in inputs:
                inp_id = inp.get("id", "")
                if not inp_id:
                    continue
                inp_type = inp.get("type", "text")
                if inp_type == "email":
                    fill_lines.append(f'        page.fill("#{inp_id}", "test@example.com")')
                elif inp_type == "number":
                    fill_lines.append(f'        page.fill("#{inp_id}", "10")')
                else:
                    fill_lines.append(f'        page.fill("#{inp_id}", "Test Value")')

            fill_block = "\n".join(fill_lines)
            test_methods.append(f'''
    def test_{slug}_submit_valid(self, page: Page):
        """Positive: submit {form_id} with valid data."""
        page.goto(BASE_URL)
{fill_block}
        page.click("#{form_id} button")
        page.wait_for_timeout(1000)
''')

            # Negative test - empty submission
            test_methods.append(f'''
    def test_{slug}_submit_empty(self, page: Page):
        """Negative: submit {form_id} with empty fields."""
        page.goto(BASE_URL)
        page.click("#{form_id} button")
        page.wait_for_timeout(1000)
''')

    # Table verification tests
    for pg in pages:
        for tbl in pg.get("tables", []):
            tbl_id = tbl.get("id", "")
            if not tbl_id:
                continue
            slug = _slugify(tbl_id)
            test_methods.append(f'''
    def test_{slug}_visible(self, page: Page):
        """Verify table {tbl_id} is present."""
        page.goto(BASE_URL)
        expect(page.locator("#{tbl_id}")).to_be_visible()
''')

    # Journey test
    if tabs:
        nav_steps = ['        page.goto(BASE_URL)']
        for tab in tabs:
            if tab["id"]:
                nav_steps.append(f'        page.click("#{tab["id"]}")')
                nav_steps.append('        page.wait_for_timeout(500)')
        nav_block = "\n".join(nav_steps)
        test_methods.append(f'''
    def test_full_navigation_journey(self, page: Page):
        """Journey: navigate through all tabs."""
        import time
        start = time.time()
{nav_block}
        total_ms = (time.time() - start) * 1000
        assert total_ms < 10000, f"Journey took {{total_ms:.0f}}ms"
''')

    # Performance test
    test_methods.append(f'''
    def test_homepage_performance(self, page: Page):
        """Performance: homepage loads within threshold."""
        import time
        start = time.time()
        page.goto(BASE_URL)
        duration_ms = (time.time() - start) * 1000
        assert duration_ms < 5000, f"Page took {{duration_ms:.0f}}ms"
''')

    methods_block = "\n".join(test_methods)

    script = f'''"""
Playwright MCP-generated tests — {app_title}
Generated from live browser interaction with {base_url}
Run with: pytest mcp_generated_test.py -v -s
"""
import os
import time
import pytest
from playwright.sync_api import Page, expect

BASE_URL = os.getenv("SFCC_SITE_URL", "{base_url}")


@pytest.fixture(scope="module")
def browser():
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    br = pw.chromium.launch(headless=True)
    yield br
    br.close()
    pw.stop()


@pytest.fixture
def page(browser):
    pg = browser.new_page()
    yield pg
    pg.close()


class TestMCPGenerated:
    """Tests generated from live browser discovery of {app_title}."""
{methods_block}
'''

    path = os.path.join(output_dir, "mcp_generated_test.py")
    _write_file(path, script)
    return [path]


def _generate_csv_driven_scripts_with_llm(
    discovery: dict,
    test_cases: list,
    output_dir: str,
) -> List[str]:
    """Mode 2: Use CSV test cases + app discovery to generate targeted Playwright tests."""
    base_url = discovery.get("url", "http://localhost:8000")

    pages_desc = []
    for pg in discovery.get("pages", []):
        desc = f"Page: {pg['name']}"
        for form in pg.get("forms", []):
            inputs_desc = ", ".join(
                f"{i['id'] or i['name']}({i['type']})" for i in form.get("inputs", []))
            desc += f"\n  Form #{form['form_id']}: inputs=[{inputs_desc}]"
        pages_desc.append(desc)

    structure = "\n".join(pages_desc)

    # Format test cases for the prompt
    cases_desc = []
    for tc in test_cases[:30]:  # Limit to avoid huge prompts
        cases_desc.append(
            f"  [{tc.type}] {tc.test_name}: {tc.method} {tc.page_or_endpoint} "
            f"input={tc.input_data} expected={tc.expected_result}"
        )
    cases_block = "\n".join(cases_desc)

    prompt = f"""Generate Playwright pytest tests based on these test cases and the app's actual UI structure.

App URL: {base_url}
App Structure (from live browser):
{structure}

Test Cases from CSV:
{cases_block}

For EACH test case, generate a Playwright test method that:
- Navigates to the correct page/tab
- For form tests: fills the actual form fields using their real IDs from the app structure
- For API tests: uses page.context.request
- Asserts the expected result
- Handles both positive and negative cases appropriately

Requirements:
- BASE_URL = os.getenv("SFCC_SITE_URL", "{base_url}")
- Use the actual element IDs from the app structure (match form inputs to test case fields)
- For negative tests, verify error handling (toast, validation message, or error status)
- Class TestCSVDriven with one method per test case
- Include proper docstrings referencing the test_id

Output ONLY valid Python code, no markdown fences."""

    try:
        response = llm_chat(prompt, temperature=0.2,
                            system="You are a QA automation expert. Map CSV test cases to real UI elements.")
        script = _strip_fences(response)
        path = os.path.join(output_dir, "mcp_csv_driven_test.py")
        _write_file(path, script)
        return [path]
    except Exception as e:
        logger.error(f"LLM CSV-driven script generation failed: {e}")
        return []


def _generate_csv_driven_scripts_template(
    discovery: dict,
    test_cases: list,
    output_dir: str,
) -> List[str]:
    """Mode 2 fallback: Generate tests from CSV cases using templates."""
    base_url = discovery.get("url", "http://localhost:8000")

    # Build a map of form_id -> inputs from discovery
    form_map = {}
    for pg in discovery.get("pages", []):
        for form in pg.get("forms", []):
            fid = form.get("form_id", "")
            if fid:
                form_map[fid] = form.get("inputs", [])

    test_methods = []
    for tc in test_cases:
        slug = _slugify(tc.test_name)
        endpoint = tc.page_or_endpoint
        method = tc.method.upper()

        try:
            input_data = json.loads(tc.input_data) if tc.input_data else {}
        except (json.JSONDecodeError, TypeError):
            input_data = {}

        if method == "FORM_SUBMIT":
            # UI form test
            form_id = endpoint.lstrip("#")
            inputs = form_map.get(form_id, [])
            fill_lines = []
            for inp in inputs:
                inp_id = inp.get("id", "")
                if not inp_id:
                    continue
                value = input_data.get(inp_id, input_data.get(inp.get("name", ""), ""))
                if value:
                    fill_lines.append(f'        page.fill("#{inp_id}", "{value}")')
            fill_block = "\n".join(fill_lines) if fill_lines else "        pass"

            test_methods.append(f'''
    def test_{slug}(self, page: Page):
        """{tc.test_id} [{tc.type}]: {tc.description}"""
        page.goto(BASE_URL)
{fill_block}
        page.click("#{form_id} button")
        page.wait_for_timeout(1000)
''')
        elif method in ("GET", "POST", "PUT", "PATCH", "DELETE"):
            # API test
            path_safe = re.sub(r'\{[^}]+\}', '1', endpoint)
            if method == "GET":
                test_methods.append(f'''
    def test_{slug}(self, page: Page):
        """{tc.test_id} [{tc.type}]: {tc.description}"""
        ctx = page.context.request
        resp = ctx.get(f"{{BASE_URL}}{path_safe}")
        {"assert resp.status == 200" if tc.type == "positive" else "assert resp.status >= 400"}
''')
            elif method == "POST":
                data_str = json.dumps(input_data)
                test_methods.append(f'''
    def test_{slug}(self, page: Page):
        """{tc.test_id} [{tc.type}]: {tc.description}"""
        ctx = page.context.request
        resp = ctx.post(f"{{BASE_URL}}{path_safe}", data={data_str})
        {"assert resp.status in (200, 201)" if tc.type == "positive" else "assert resp.status >= 400"}
''')
            elif method == "DELETE":
                test_methods.append(f'''
    def test_{slug}(self, page: Page):
        """{tc.test_id} [{tc.type}]: {tc.description}"""
        ctx = page.context.request
        resp = ctx.delete(f"{{BASE_URL}}{path_safe}")
        {"assert resp.status in (200, 204)" if tc.type == "positive" else "assert resp.status >= 400"}
''')
            else:
                data_str = json.dumps(input_data)
                test_methods.append(f'''
    def test_{slug}(self, page: Page):
        """{tc.test_id} [{tc.type}]: {tc.description}"""
        ctx = page.context.request
        resp = ctx.{method.lower()}(f"{{BASE_URL}}{path_safe}", data={data_str})
        {"assert resp.status == 200" if tc.type == "positive" else "assert resp.status >= 400"}
''')

    methods_block = "\n".join(test_methods)

    script = f'''"""
Playwright CSV-Driven Tests
Generated from test_cases.csv + live browser discovery
Run with: pytest mcp_csv_driven_test.py -v -s
"""
import os
import pytest
from playwright.sync_api import Page, expect

BASE_URL = os.getenv("SFCC_SITE_URL", "{base_url}")


@pytest.fixture(scope="module")
def browser():
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    br = pw.chromium.launch(headless=True)
    yield br
    br.close()
    pw.stop()


@pytest.fixture
def page(browser):
    pg = browser.new_page()
    yield pg
    pg.close()


class TestCSVDriven:
    """Tests driven by CSV test cases, mapped to real UI elements."""
{methods_block}
'''

    path = os.path.join(output_dir, "mcp_csv_driven_test.py")
    _write_file(path, script)
    return [path]


def _strip_fences(code: str) -> str:
    lines = code.splitlines()
    fence_indices = [i for i, l in enumerate(lines) if l.strip().startswith("```")]
    if len(fence_indices) >= 2:
        return "\n".join(lines[fence_indices[0] + 1:fence_indices[-1]]).strip()
    return code


def generate_mcp_tests(
    base_url: str,
    output_dir: str,
    csv_path: Optional[str] = None,
) -> List[str]:
    """
    Main entry point for MCP test generation.

    Args:
        base_url: URL of the running target application
        output_dir: Where to write generated test files
        csv_path: If provided (Mode 2), use CSV test cases to drive generation

    Returns:
        List of paths to generated test files
    """
    logger.info(f"MCP test generation starting — target: {base_url}")
    logger.info(f"Discovering app structure via Playwright...")

    discovery = _discover_app(base_url)
    if not discovery:
        logger.error("App discovery failed — is the target app running?")
        return []

    pages = discovery.get("pages", [])
    tabs = discovery.get("tabs", [])
    total_forms = sum(len(p.get("forms", [])) for p in pages)
    total_tables = sum(len(p.get("tables", [])) for p in pages)
    logger.info(
        f"Discovered: {len(pages)} pages, {len(tabs)} tabs, "
        f"{total_forms} forms, {total_tables} tables"
    )

    generated = []

    if csv_path:
        # Mode 2: CSV-driven
        from agent.test_case_generator import load_test_cases
        test_cases = load_test_cases(csv_path)
        logger.info(f"Loaded {len(test_cases)} test cases from {csv_path}")

        if llm_available():
            generated = _generate_csv_driven_scripts_with_llm(discovery, test_cases, output_dir)
        if not generated:
            generated = _generate_csv_driven_scripts_template(discovery, test_cases, output_dir)
    else:
        # Mode 1: Pure MCP discovery
        if llm_available():
            generated = _generate_mcp_scripts_with_llm(discovery, output_dir)
        if not generated:
            generated = _generate_mcp_scripts_template(discovery, output_dir)

    logger.info(f"MCP generation complete — {len(generated)} files written")
    return generated
