"""
tools/k6.py
───────────
Runs k6 scripts and pushes metrics to Prometheus (local Docker or Cloud).

Local Docker mode  → k6 pushes to http://prometheus:9090/api/v1/write
                     No username/password needed.
Grafana Cloud mode → k6 pushes to Grafana remote-write URL with credentials.

The mode is detected automatically from K6_PROMETHEUS_RW_SERVER_URL:
  - contains "prometheus:" or "localhost" → local Docker, no auth
  - anything else with a real URL         → cloud, use credentials
"""

import os
import glob
import subprocess
import logging
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# Read at call time (not module load) so docker-compose env overrides work
def _get_rw_url():
    return os.getenv("K6_PROMETHEUS_RW_SERVER_URL") or os.getenv("GRAFANA_RW_URL", "")

def _get_rw_user():
    return os.getenv("K6_PROMETHEUS_RW_USERNAME") or os.getenv("GRAFANA_USERNAME", "")

def _get_rw_pass():
    return os.getenv("K6_PROMETHEUS_RW_PASSWORD") or os.getenv("GRAFANA_API_KEY", "")

SFCC_SITE_URL = os.getenv("SFCC_SITE_URL", "")

# Placeholder markers — fall back to test.k6.io if URL is not a real app
_PLACEHOLDER_MARKERS = ("your-sfcc-site", "your-app", "example.com", "")

def _effective_target_url():
    url = os.getenv("SFCC_SITE_URL", "")
    if url and not any(m in url for m in _PLACEHOLDER_MARKERS):
        return url
    return "https://test.k6.io"

# Demo scripts generated by the fixture demo — never run in real pipeline
# Also exclude test_generated, test_concurrent, and blackbox fixture folders
DEMO_SCRIPT_PATTERNS = ["api_wishlist", "api_wishlist_user_id"]
DEMO_SCRIPT_DIRS     = ["test_generated", "test_concurrent", "blackbox-test_fixture"]


# ── Logging ───────────────────────────────────────────────────────────────────

def _setup_logger() -> logging.Logger:
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file  = os.path.join("logs", f"k6_run_{timestamp}.log")

    # Use a unique logger name per run to avoid duplicate handlers
    logger = logging.getLogger(f"k6_{timestamp}")
    logger.setLevel(logging.DEBUG)

    fh = logging.FileHandler(log_file, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))

    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(message)s"))

    logger.addHandler(fh)
    logger.addHandler(ch)
    logger.info(f"[k6] Log file: {log_file}")
    return logger


def _is_local_prometheus(rw_url: str) -> bool:
    """True when pushing to a local Docker Prometheus (no auth needed)."""
    return any(h in rw_url for h in ("prometheus:", "localhost", "127.0.0.1"))


def _prometheus_configured(rw_url: str) -> bool:
    """True when a real remote-write URL is set (local or cloud)."""
    return bool(rw_url) and "xxxxx" not in rw_url and rw_url.startswith("http")


def _is_demo_script(path: str) -> bool:
    name = os.path.basename(path)
    # Exclude by filename pattern
    if any(p in name for p in DEMO_SCRIPT_PATTERNS):
        return True
    # Exclude by directory
    normalized = path.replace("\\", "/")
    if any(f"/{d}/" in normalized or normalized.startswith(f"{d}/") for d in DEMO_SCRIPT_DIRS):
        return True
    return False


# ── Public API ────────────────────────────────────────────────────────────────

def run_k6_test(script_dir: str = "scripts") -> dict:
    """
    Run all real k6 scripts under script_dir.
    Supports both old flat layout and new repo/env/k6/ layout.
    Pushes metrics to local Prometheus or Grafana Cloud automatically.
    """
    logger = _setup_logger()

    # Read env at call time so docker-compose overrides are picked up
    rw_url  = _get_rw_url()
    rw_user = _get_rw_user()
    rw_pass = _get_rw_pass()
    target  = _effective_target_url()

    env = os.environ.copy()
    env["SFCC_SITE_URL"] = target
    logger.info(f"[k6] Target app URL : {target}")

    use_prometheus = _prometheus_configured(rw_url)
    local_mode     = _is_local_prometheus(rw_url) if use_prometheus else False

    if use_prometheus:
        env["K6_PROMETHEUS_RW_SERVER_URL"] = rw_url
        if not local_mode:
            # Cloud needs auth
            env["K6_PROMETHEUS_RW_USERNAME"] = rw_user
            env["K6_PROMETHEUS_RW_PASSWORD"] = rw_pass
            logger.info(f"[k6] Grafana Cloud remote-write → {rw_url}")
        else:
            # Local Prometheus — clear any leftover cloud credentials
            env.pop("K6_PROMETHEUS_RW_USERNAME", None)
            env.pop("K6_PROMETHEUS_RW_PASSWORD", None)
            logger.info(f"[k6] Local Prometheus remote-write → {rw_url}")
    else:
        logger.info("[k6] No Prometheus configured — running without metrics push")

    # Find scripts
    all_scripts  = sorted(glob.glob(f"{script_dir}/**/*.js", recursive=True))
    real_scripts = [s for s in all_scripts if not _is_demo_script(s)]
    skipped      = [s for s in all_scripts if _is_demo_script(s)]

    for s in skipped:
        logger.info(f"[k6] Skipping demo script: {s}")

    if not real_scripts:
        logger.warning("[k6] No scripts found")
        return {"status": "no_scripts", "scripts_run": 0, "results": []}

    results = []

    for script in real_scripts:
        logger.info(f"\n-----------------------------------")
        logger.info(f"[k6] Running: {script}")
        logger.info(f"-----------------------------------")

        cmd = ["k6", "run"]
        if use_prometheus:
            cmd += ["-o", "experimental-prometheus-rw"]
        cmd.append(script)

        try:
            proc = subprocess.run(
                cmd, env=env, capture_output=True, text=True, timeout=300
            )

            if proc.stdout:
                logger.debug(proc.stdout)
            if proc.stderr:
                logger.debug(proc.stderr)

            label = "passed" if proc.returncode == 0 else "FAILED"
            logger.info(f"[k6] {script} → {label} (exit {proc.returncode})")

            results.append({
                "script":    script,
                "exit_code": proc.returncode,
                "stdout":    proc.stdout[-2000:],
                "stderr":    proc.stderr[-500:],
            })

        except subprocess.TimeoutExpired:
            logger.error(f"[k6] {script} → TIMEOUT")
            results.append({"script": script, "exit_code": -1, "error": "timeout"})

        except FileNotFoundError:
            logger.error("[k6] k6 binary not found")
            return {
                "status":      "k6_not_installed",
                "error":       "k6 binary not found. Install from https://k6.io/docs/getting-started/installation/",
                "scripts_run": 0,
                "results":     [],
            }

    failed = [r for r in results if r.get("exit_code", 1) != 0]
    logger.info(f"[k6] Done — {len(results)} scripts, {len(failed)} failed")

    return {
        "status":       "completed" if not failed else "failed",
        "scripts_run":  len(results),
        "failed_count": len(failed),
        "results":      results,
    }
